const rooms = [
    {
        roomNo: 1,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 2,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 3,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 4,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 5,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 6,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 7,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 8,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 9,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 10,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 11,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 12,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 13,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 14,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 15,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 16,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 17,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 18,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 19,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 20,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 21,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 22,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 23,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 24,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 25,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 26,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 27,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 28,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 29,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 30,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 31,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 32,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 33,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 34,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 35,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 36,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 37,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 38,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 39,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 40,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 41,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 42,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 43,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 44,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 45,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 46,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 47,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
    {
        roomNo: 48,
        price: 1234,
        book: "unoccupied",
        cleaningStatus: "cleaned",
    },
];
module.exports = rooms;